### ISSUE TITLE
Top panel has unnecessary space on Windows when taskbar is pinned to the left side

### ISSUE THREAD

**Issue by abaksha-sc** [Ruben2776/PicView#261]
**Describe the bug**
I use Windows and my taskbar is pinned to the left. In this case top panel has some unnecessary space and I cannot close the window with just blind movement of cursor to the right (it suggests to resize window).

<img width="448" height="269" alt="Image" src="https://github.com/user-attachments/assets/b1f38430-38c7-49ef-a2a6-7aff4f3b29ba" />

(sorry for the photo but I don't know how to make screenshot with mouse cursor :) )

<img width="1920" height="172" alt="Image" src="https://github.com/user-attachments/assets/679d743c-62a0-4cfd-b37b-d7f34e440fc6" />
. 

**To Reproduce**
1. On Windows move taskbar to the left 

<img width="522" height="471" alt="Image" src="https://github.com/user-attachments/assets/f41652a6-66dd-4751-975e-803b4734ddab" />

2. Open any image with PicView and maximize the window with double click on window header
3. Move mouse cursor to the top right corner of the screen

**Expected behavior**
Button "Close window" is under cursor and no extra space is around top panel as when taskbar is at the bottom:

<img width="303" height="139" alt="Image" src="https://github.com/user-attachments/assets/ae8db3e6-1b8b-4c8b-a9f9-01460cf46c0c" />

**Additional context**
PicView v3.2.0.1
OS Windows 10, but taskbar is pinned to the left side.
Monitor is just 1920x1080 px withouth any high-dpi scalings

P.S. The same problem with the bottom panel:

<img width="1920" height="84" alt="Image" src="https://github.com/user-attachments/assets/6c713ad7-6a15-4484-a5bd-03ac1a87b93a" />

**Comment by Ruben2776** [comment]
Hi there, thank you for the bug report.

This has already been fixed by mghe01 in a recent pull request: https://github.com/Ruben2776/PicView/pull/255

If you want to test it, you can download it below, at the bottom of the page while being logged in to GitHub (_You can delete `.pdb` to save disk space from these builds_):
https://github.com/Ruben2776/PicView/actions/runs/18631398220

**Comment by abaksha-sc** [comment]
@Ruben2776 seems like it's not fixed. It looks better but still 1px doesn't allow to close the window 😢 Maybe there is some border?
(tested portable build PicView-v3.2.0.1-win-x64.zip)

<img width="408" height="257" alt="Image" src="https://github.com/user-attachments/assets/75986c95-1ff7-44be-b17c-535046aac413" />

<img width="660" height="422" alt="Image" src="https://github.com/user-attachments/assets/4d9ccac2-02be-4f61-9d8d-58494d1c11b5" />

**Comment by abaksha-sc** [comment]
@Ruben2776 Oh, but I found that when option "Auto-fit window" is disabled then works fine (on the latest prod version).
So as for me the issue is resolved

<img width="503" height="273" alt="Image" src="https://github.com/user-attachments/assets/5be41d24-0e49-4fd2-bb74-454756bc2d1b" />

-separator-
-separator-
    
  
### **UPD: but it appears again on the version from PR (1px border) independent of option "Auto-fit window"**

<img width="823" height="354" alt="Image" src="https://github.com/user-attachments/assets/c5c08fa7-b45a-4138-8d4a-5dde26532132" />

**Comment by Ruben2776** [comment]
@abaksha-sc Sorry for the late response. Do you still experience any issues in the new 4.0 version?

**Comment by abaksha-sc** [comment]
It's ok on the prod version 3.2.0.1 with disabled option "Auto-fit window", but appears on the PR version you provided here: https://github.com/Ruben2776/PicView/issues/261#issuecomment-3436541743 - screenshot in my prev message above

So makes sense to test and fix PR version before release
